### ISSUE TITLE
Binary file 'template' in project

### ISSUE THREAD

**Issue by fearofcode** [erroneousboat/docker-django#10]
https://github.com/erroneousboat/docker-django/blob/master/config/utils/template/template is apparently a binary? May I ask what it is and where it came from?

Please close if this is not an issue. Thanks!

**Comment by jpbruinsslot** [comment]
@fearofcode Ofcourse :) It's from a program I wrote: https://github.com/erroneousboat/template

**Comment by fearofcode** [comment]
Ah. I see. Would it be an improvement to have Docker build that from source rather than including a binary in the repo?

I can't commit to carrying that out, but I'm currently trying to learn Docker, so that would be a nice, well-defined project for someone to contribute to this repo.

For now, closing this.

Thanks for the fast response!

**Comment by jpbruinsslot** [comment]
Yeah you're right however I wanted to dynamically create a nginx config file based on specific settings (production or development). Other options could be:
1. copying config files into the container
2. attaching a volume with the config
3. using `envsubst`

source: https://hub.docker.com/_/nginx/

I just learned about the third option, because of your question. When I started this project the `envsubst` option wasn't known to me. So I'll look into that as an alternative. Thanks for the question and I'll reopen the issue to check it out.
