### ISSUE TITLE
Question: why install uWSGI in the webapp and no the webserver?

### ISSUE THREAD

**Issue by dmenisdev** [erroneousboat/docker-django#19]
Question: why install uWSGI in the webapp and no the webserver?

**Comment by jpbruinsslot** [comment]
I'm not sure if I understand your question correctly. But since uwsgi is the application server that actually loads and runs the webapp, in my opinion it should be packaged along side the webapp. Nginx here serves as a reverse proxy that relays requests to uwsgi. Hope that answers your question, and reiterate what is said in the readme, I don't claim that this is a 100% correct setup, there are always different opinions, considerations, and methods and I advice you to  seek out different setups to see what works best for your use case. Cheers

**Comment by dmenisdev** [comment]
Thanks I think you are correct it is the only logical place and probably the only option :).
